Add storybook and first stories
Storybook install

https://www.gatsbyjs.com/docs/how-to/testing/visual-testing-with-storybook/#storybook-version-5

storybook-webpack upgrade

https://gist.github.com/shilman/8856ea1786dcd247139b47b270912324#upgrading-from-webpack-4

update gatsby 3.2.1->3.7.0

prior the update `npm run storybook` was throwing:
ERR! Error: Cannot find module 'babel-plugin-remove-graphql-queries'
this seems to fix it

Configurations for the chakra ui styles to load up

https://dev.to/carlosrafael22/what-i-ve-learned-with-chakra-ui-so-far-4f5e
https://chakra-ui.com/docs/getting-started#set-up-provider

refactor /ui components, and write first stories

add CharacterView stories

minor visual update to CharacterView

npm re-install

`gatsby develop` was throwing "gatsby TypeError: The 'compilation' argument must be an instance of Compilation"
as per: https://github.com/gatsbyjs/gatsby/discussions/30124#discussioncomment-454993
deleted node_modules, package-lock; npm install

minor visual update to CharacterView

for some reason CharacterView `edit & delete` buttons where not having
rounded corners (chakra-ui default), re-adding that + other minor styles

add characterFrom stories

Fix several testing-library and cypress tests

add cy:run:nomedia to package.js

 cy:run is slower and it often fails tests in my current machine